stages:
  load_data:
    cmd: python src/stage_01_load_save.py --config=config/config.yaml
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_local_dir/data.csv

  split_data:
    cmd: python src/stage_02_split_data.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_02_split_data.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/raw_local_dir/data.csv
    params:
      - base.random_state
      - base.test_size
    outs:
      - artifacts/split_data_dir/train.csv
      - artifacts/split_data_dir/test.csv
  tune:
    cmd: python src/stage_04_tune.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_01_load_save.py  
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/raw_local_dir/data.csv
    params:
      - base.random_state
      - hyper_params.ElasticNet.alpha
      - hyper_params.ElasticNet.l1_ratio
    outs:
      - artifacts/hyperparams_dir/best_parameters.json
  train:
    cmd: python src/stage_03_train.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_04_tune.py
      - src/stage_03_train.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/split_data_dir/train.csv
      - artifacts/hyperparams_dir/best_parameters.json
    params:
      - base.random_state
      - model_params.ElasticNet.alpha
      - model_params.ElasticNet.l1_ratio
    outs:
      - artifacts/model_dir/ElasticNet.model

  evaluate:
    cmd: python src/stage_05_evaluate.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_05_evaluate.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/split_data_dir/test.csv
      - artifacts/model_dir/ElasticNet.model
    outs:
      - artifacts/reports_dir/scores.json   